terimler_app_web/terimler_app_web/Controllers/Site/YonetimYoneticilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using terimler_app_web.DataAccessLayer.Concrete;
using terimler_app_web.Filter;
using terimler_app_web.Models.Concrete;

namespace terimler_app_web.Controllers.Site
{
    [AuthFilter]
    public class YonetimYoneticilerController : Controller
    {

        YoneticilerOperations yoneticilerOperations = new YoneticilerOperations("Yoneticiler");

        public IActionResult Index()
        {
            return View(yoneticilerOperations.GetAll().OrderByDescending(x => x.Id));
        }

        public IActionResult Incele(int id)
        {
            var item = yoneticilerOperations.GetById(id);
            if (item == null)
            {
                return RedirectToAction("Yonetim", "Hata");
            }
            return View(item);
        }

        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(Yoneticiler model)
        {
            if (ModelState.IsValid)
            {
                yoneticilerOperations.AddModel(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult Guncelle(int id)
        {
            var item = yoneticilerOperations.GetById(id);
            if (item == null)
            {
                return RedirectToAction("Yonetim", "Hata");
            }
            return View(item);
        }

        [HttpPost]
        public IActionResult Guncelle(int id, Yoneticiler newModel)
        {
            var model = yoneticilerOperations.GetById(id);

            model.KullaniciAdi = newModel.KullaniciAdi;
            model.Sifre = newModel.Sifre;

            yoneticilerOperations.UpdateModel(model);

            return RedirectToAction("Index");
        }

        public IActionResult Sil(int id)
        {
            var item = yoneticilerOperations.GetById(id);
            if (item == null)
            {
                return RedirectToAction("Yonetim", "Hata");
            }
            return View(item);
        }

        [HttpPost]
        public IActionResult Sil(int id, IFormCollection collection)
        {
            yoneticilerOperations.DeleteModel(id);
            return RedirectToAction("Index");
        }
    }
}

terimler_app_web/terimler_app_web/Views/YonetimYoneticiler/Ekle.cshtml
@model Yoneticiler
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<div class="card">
    <div class="card-heading border bottom">
        <br />
        <h4 class="card-title text-center">Yeni Yönetici Ekle</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-md-9 ml-auto mr-auto">
                <form asp-controller="YonetimYoneticiler" asp-action="Ekle" method="post" enctype="multipart/form-data" class="form-horizontal mrg-top-40 pdd-right-30 ng-pristine ng-valid">
                    <div class="form-group">
                        <br />
                        <label>Kullanıcı Adı</label>
                        <input type="text" class="form-control" asp-for="KullaniciAdi" placeholder="Kullanıcı Adını Giriniz..." required>
                    </div>
                    <div class="form-group">
                        <label>Şifre</label>
                        <input type="text" class="form-control" asp-for="Sifre" placeholder="Şifreyi Giriniz..." required>
                    </div>
                    <center><button type="submit" class="btn btn-info"><i class="fa fa-plus" aria-hidden="true"></i> Yeni Yönetici Ekle</button></center><br />
                </form>
            </div>
        </div>
    </div>
</div>

terimler_app_web/terimler_app_web/Views/YonetimYoneticiler/Guncelle.cshtml
@model Yoneticiler
@{
    ViewData["Title"] = "Guncelle";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<div class="card">
    <div class="card-heading border bottom">
        <br />
        <h4 class="card-title text-center">Yönetici Güncelle</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-md-9 ml-auto mr-auto">
                <form asp-controller="YonetimYoneticiler" asp-action="Guncelle" method="post" enctype="multipart/form-data" class="form-horizontal mrg-top-40 pdd-right-30 ng-pristine ng-valid">
                    <div class="form-group">
                        <br />
                        <label>Kullanıcı Adı</label>
                        <input type="text" class="form-control" asp-for="KullaniciAdi" value="@Model.KullaniciAdi" required>
                    </div>
                    <div class="form-group">
                        <label>Şifre</label>
                        <input type="text" class="form-control" asp-for="Sifre" value="@Model.Sifre" required>
                    </div>
                    <center><button type="submit" class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i> Yönetici Güncelle</button></center><br />
                </form>
            </div>
        </div>
    </div>
</div>

terimler_app_web/terimler_app_web/Views/YonetimYoneticiler/Incele.cshtml
@model Yoneticiler
@{
    ViewData["Title"] = "Incele";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<div class="card">
    <div class="card-heading border bottom">
        <br />
        <h4 class="card-title text-center">Yönetici İncele</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-md-9 ml-auto mr-auto">
                <form asp-controller="" asp-action="" method="post" enctype="multipart/form-data" class="form-horizontal mrg-top-40 pdd-right-30 ng-pristine ng-valid">
                    <div class="form-group">
                        <br />
                        <label>Kullanıcı Adı</label>
                        <input type="text" class="form-control" asp-for="KullaniciAdi" value="@Model.KullaniciAdi" readonly>
                    </div>
                    <div class="form-group">
                        <label>Şifre</label>
                        <input type="text" class="form-control" asp-for="Sifre" value="@Model.Sifre" readonly>
                    </div>
                </form>
                <center><a href="/YonetimYoneticiler/Index/" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Geriye Dön</a></center><br />
            </div>
        </div>
    </div>
</div>

terimler_app_web/terimler_app_web/Views/YonetimYoneticiler/Index.cshtml
@model IEnumerable<Yoneticiler>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<script src="~/TemplateAdmin/Js/jquery-1.10.2.js"></script>
<script>
    $(document).ready(function () {
        $('#myTable').dataTable();
    });
</script>

<div class="container-fluid">
    @if (Model.Count() > 0)
    {
        <!-- Verileri Listeleme -->
        <div class="card mb-3 text-center">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Yöneticiler Listesi
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="myTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Kullanıcı Adı</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.KullaniciAdi</td>
                                    <td>
                                        <a href="/YonetimYoneticiler/Incele/@item.Id" class="btn btn-info btn-sm"><i class="fa fa-search" aria-hidden="true"></i> İncele</a>
                                        <a href="/YonetimYoneticiler/Guncelle/@item.Id" class="btn btn-success btn-sm"><i class="fa fa-wrench" aria-hidden="true"></i> Güncelle</a>
                                        <a href="/YonetimYoneticiler/Sil/@item.Id" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i> Sil</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer small text-muted">Son Güncelleme Tarihi : @DateTime.Now</div>
        </div>

    }
    else
    {
        <div class="card mb-3 text-center">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Veri Bulunamadı
            </div>
            <div class="card-body">
                Eklenmiş Herhangi Bir Veri Bulunamadı...
            </div>
        </div>
    }
</div>

terimler_app_web/terimler_app_web/Views/YonetimYoneticiler/Sil.cshtml
@model Yoneticiler
@{
    ViewData["Title"] = "Sil";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<div class="card">
    <div class="card-heading border bottom">
        <br />
        <h4 class="card-title text-center">Yönetici Sil</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-md-9 ml-auto mr-auto">
                <form asp-controller="YonetimYoneticiler" asp-action="Sil" method="post" enctype="multipart/form-data" class="form-horizontal mrg-top-40 pdd-right-30 ng-pristine ng-valid">
                    <div class="form-group">
                        <br />
                        <label>Kullanıcı Adı</label>
                        <input type="text" class="form-control" asp-for="KullaniciAdi" value="@Model.KullaniciAdi" readonly>
                    </div>
                    <div class="form-group">
                        <label>Şifre</label>
                        <input type="text" class="form-control" asp-for="Sifre" value="@Model.Sifre" readonly>
                    </div>
                    <center><button type="submit" class="btn btn-danger"><i class="fa fa-plus" aria-hidden="true"></i> Yönetici Sil</button></center><br />
                </form>
            </div>
        </div>
    </div>
</div>