terimler_app_web/terimler_app_web/Controllers/Site/YonetimMesajlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using terimler_app_web.DataAccessLayer.Concrete;
using terimler_app_web.Filter;
using terimler_app_web.Models.Concrete;

namespace terimler_app_web.Controllers.Site
{
    [AuthFilter]
    public class YonetimMesajlarController : Controller
    {

        MesajlarOperations mesajlarOperations = new MesajlarOperations("Mesajlar");

        public IActionResult Index()
        {
            return View(mesajlarOperations.GetAll().OrderByDescending(x => x.Id));
        }

        public IActionResult Incele(int id)
        {
            var item = mesajlarOperations.GetById(id);
            if (item == null)
            {
                return RedirectToAction("Yonetim", "Hata");
            }
            return View(item);
        }

        public IActionResult Sil(int id)
        {
            var item = mesajlarOperations.GetById(id);
            if (item == null)
            {
                return RedirectToAction("Yonetim", "Hata");
            }
            return View(item);
        }

        [HttpPost]
        public IActionResult Sil(int id, IFormCollection collection)
        {
            mesajlarOperations.DeleteModel(id);
            return RedirectToAction("Index");
        }

    }
}

terimler_app_web/terimler_app_web/Views/YonetimMesajlar/Incele.cshtml
@model Mesajlar
@{
    ViewData["Title"] = "Incele";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<div class="card">
    <div class="card-heading border bottom">
        <br />
        <h4 class="card-title text-center">Mesaj İncele</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-md-9 ml-auto mr-auto">
                <form asp-controller="" asp-action="" method="post" enctype="multipart/form-data" class="form-horizontal mrg-top-40 pdd-right-30 ng-pristine ng-valid">
                    <div class="form-group">
                        <br />
                        <label>Gönderici Ad Soyad</label>
                        <input type="text" class="form-control" asp-for="AdSoyad" value="@Model.AdSoyad" readonly>
                    </div>
                    <div class="form-group">
                        <label>Gönderici Mail Adresi</label>
                        <input type="text" class="form-control" asp-for="Mail" value="@Model.Mail" readonly>
                    </div>
                    <div class="form-group">
                        <label>Gönderim Tarihi</label>
                        <input type="text" class="form-control" asp-for="Tarih" value="@Model.Tarih" readonly>
                    </div>
                    <div class="form-group">
                        <label>Mesaj Başlık</label>
                        <input type="text" class="form-control" asp-for="Baslik" value="@Model.Baslik" readonly>
                    </div>
                    <div class="form-group">
                        <label>Mesaj İçerik</label>
                        <textarea class="form-control" asp-for="Icerik" rows="5" readonly>@Model.Icerik</textarea>
                    </div>
                </form>
                <center><a href="/YonetimMesajlar/Index/" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Geriye Dön</a></center><br />
            </div>
        </div>
    </div>
</div>

terimler_app_web/terimler_app_web/Views/YonetimMesajlar/Index.cshtml
@model IEnumerable<Mesajlar>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<script src="~/TemplateAdmin/Js/jquery-1.10.2.js"></script>
<script>
    $(document).ready(function () {
        $('#myTable').dataTable();
    });
</script>

<div class="container-fluid">
    @if (Model.Count() > 0)
    {
        <!-- Verileri Listeleme -->
        <div class="card mb-3 text-center">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Gelen Mesajlar Listesi
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="myTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Gönderici Ad Soyad</th>
                                <th>Gönderim Tarihi</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.AdSoyad</td>
                                    <td>@item.Tarih</td>
                                    <td>
                                        <a href="/YonetimMesajlar/Incele/@item.Id" class="btn btn-info btn-sm"><i class="fa fa-search" aria-hidden="true"></i> İncele</a>
                                        <a href="/YonetimMesajlar/Sil/@item.Id" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i> Sil</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer small text-muted">Son Güncelleme Tarihi : @DateTime.Now</div>
        </div>

    }
    else
    {
        <div class="card mb-3 text-center">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Veri Bulunamadı
            </div>
            <div class="card-body">
                Eklenmiş Herhangi Bir Veri Bulunamadı...
            </div>
        </div>
    }
</div>

terimler_app_web/terimler_app_web/Views/YonetimMesajlar/Sil.cshtml
@model Mesajlar
@{
    ViewData["Title"] = "Sil";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<div class="card">
    <div class="card-heading border bottom">
        <br />
        <h4 class="card-title text-center">Mesaj Sil</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-md-9 ml-auto mr-auto">
                <form asp-controller="YonetimMesajlar" asp-action="Sil" method="post" enctype="multipart/form-data" class="form-horizontal mrg-top-40 pdd-right-30 ng-pristine ng-valid">
                    <div class="form-group">
                        <br />
                        <label>Gönderici Ad Soyad</label>
                        <input type="text" class="form-control" asp-for="AdSoyad" value="@Model.AdSoyad" readonly>
                    </div>
                    <div class="form-group">
                        <label>Gönderici Mail Adresi</label>
                        <input type="text" class="form-control" asp-for="Mail" value="@Model.Mail" readonly>
                    </div>
                    <div class="form-group">
                        <label>Gönderim Tarihi</label>
                        <input type="text" class="form-control" asp-for="Tarih" value="@Model.Tarih" readonly>
                    </div>
                    <div class="form-group">
                        <label>Mesaj Başlık</label>
                        <input type="text" class="form-control" asp-for="Baslik" value="@Model.Baslik" readonly>
                    </div>
                    <div class="form-group">
                        <label>Mesaj İçerik</label>
                        <textarea class="form-control" asp-for="Icerik" rows="5" readonly>@Model.Icerik</textarea>
                    </div>
                    <center><button type="submit" class="btn btn-danger"><i class="fa fa-plus" aria-hidden="true"></i> Mesaj Sil</button></center><br />
                </form>
            </div>
        </div>
    </div>
</div>