terimler_app_web/terimler_app_web/Controllers/Site/YonetimOnerilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using terimler_app_web.DataAccessLayer.Concrete;
using terimler_app_web.Filter;
using terimler_app_web.Models.Concrete;

namespace terimler_app_web.Controllers.Site
{
    [AuthFilter]
    public class YonetimOnerilerController : Controller
    {

        OnerilerOperations onerilerOperations = new OnerilerOperations("Oneriler");

        public IActionResult Index()
        {
            return View(onerilerOperations.GetAll().OrderByDescending(x => x.Id));
        }

        public IActionResult Incele(int id)
        {
            var item = onerilerOperations.GetById(id);
            if (item == null)
            {
                return RedirectToAction("Yonetim", "Hata");
            }
            return View(item);
        }

        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(Oneriler model)
        {
            if (ModelState.IsValid)
            {
                onerilerOperations.AddModel(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult Sil(int id)
        {
            var item = onerilerOperations.GetById(id);
            if (item == null)
            {
                return RedirectToAction("Yonetim", "Hata");
            }
            return View(item);
        }

        [HttpPost]
        public IActionResult Sil(int id, IFormCollection collection)
        {
            onerilerOperations.DeleteModel(id);
            return RedirectToAction("Index");
        }

    }
}

terimler_app_web/terimler_app_web/Views/YonetimOneriler/Ekle.cshtml
@model Oneriler
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<div class="card">
    <div class="card-heading border bottom">
        <br />
        <h4 class="card-title text-center">Yeni Terim Önerisi Ekle</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-md-9 ml-auto mr-auto">
                <form asp-controller="YonetimOneriler" asp-action="Ekle" method="post" enctype="multipart/form-data" class="form-horizontal mrg-top-40 pdd-right-30 ng-pristine ng-valid">
                    <div class="form-group">
                        <br />
                        <label>Gönderen Ad Soyad</label>
                        <input type="text" class="form-control" asp-for="AdSoyad" placeholder="Gönderici Adını Giriniz..." required>
                    </div>
                    <div class="form-group">
                        <label>Gönderen Mail</label>
                        <input type="text" class="form-control" asp-for="Mail" placeholder="Gönderici Mailini Giriniz..." required>
                    </div>
                    <div class="form-group">
                        <label>Terim Adı</label>
                        <input type="text" class="form-control" asp-for="TerimAd" placeholder="Terim Adını Giriniz..." required>
                    </div>
                    <div class="form-group">
                        <label>Terim Açıklaması</label>
                        <textarea class="form-control" asp-for="TerimAciklama" placeholder="Terim Açıklamasını Giriniz..." rows="5" required></textarea>
                    </div>
                    <div class="form-group">
                        <label>Terim Bölümü</label>
                        <select class="form-control" asp-for="TerimBolum">
                            <option>Bilgisayar</option>
                            <option>Elektrik</option>
                            <option>Endüstri</option>
                            <option>Makine</option>
                            <option>Kimya</option>
                        </select>
                    </div>
                    <center><button type="submit" class="btn btn-info"><i class="fa fa-plus" aria-hidden="true"></i> Yeni Terim Önerisi Ekle</button></center><br />
                </form>
            </div>
        </div>
    </div>
</div>

terimler_app_web/terimler_app_web/Views/YonetimOneriler/Incele.cshtml
@model Oneriler
@{
    ViewData["Title"] = "Incele";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<div class="card">
    <div class="card-heading border bottom">
        <br />
        <h4 class="card-title text-center">Terim Önerisi İncele</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-md-9 ml-auto mr-auto">
                <form asp-controller="" asp-action="" method="post" enctype="multipart/form-data" class="form-horizontal mrg-top-40 pdd-right-30 ng-pristine ng-valid">
                    <div class="form-group">
                        <br />
                        <label>Gönderen Ad Soyad</label>
                        <input type="text" class="form-control" asp-for="AdSoyad" value="@Model.AdSoyad" readonly>
                    </div><div class="form-group">
                        <label>Gönderen Mail</label>
                        <input type="text" class="form-control" asp-for="Mail" value="@Model.Mail" readonly>
                    </div>
                    <div class="form-group">
                        <label>Terim Adı</label>
                        <input type="text" class="form-control" asp-for="TerimAd" value="@Model.TerimAd" readonly>
                    </div>
                    <div class="form-group">
                        <label>Terim Açıklaması</label>
                        <textarea class="form-control" asp-for="TerimAciklama" rows="5" readonly>@Model.TerimAciklama</textarea>
                    </div>
                    <div class="form-group">
                        <label>Terim Bölümü</label>
                        <input type="text" class="form-control" asp-for="TerimBolum" value="@Model.TerimBolum" readonly>
                    </div>
                </form>
                <center><a href="/YonetimOneriler/Index/" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Geriye Dön</a></center><br />
            </div>
        </div>
    </div>
</div>

terimler_app_web/terimler_app_web/Views/YonetimOneriler/Index.cshtml
@model IEnumerable<Oneriler>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<script src="~/TemplateAdmin/Js/jquery-1.10.2.js"></script>
<script>
    $(document).ready(function () {
        $('#myTable').dataTable();
    });
</script>

<div class="container-fluid">
    @if (Model.Count() > 0)
    {
        <!-- Verileri Listeleme -->
        <div class="card mb-3 text-center">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Terim Önerileri Listesi
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="myTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Ad Soyad</th>
                                <th>Terim Ad</th>
                                <th>Bölüm</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.AdSoyad</td>
                                    <td>@item.TerimAd</td>
                                    <td>@item.TerimBolum</td>
                                    <td>
                                        <a href="/YonetimOneriler/Incele/@item.Id" class="btn btn-info btn-sm"><i class="fa fa-search" aria-hidden="true"></i> İncele</a>
                                        <a href="/YonetimOneriler/Sil/@item.Id" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i> Sil</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer small text-muted">Son Güncelleme Tarihi : @DateTime.Now</div>
        </div>

    }
    else
    {
        <div class="card mb-3 text-center">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Veri Bulunamadı
            </div>
            <div class="card-body">
                Eklenmiş Herhangi Bir Veri Bulunamadı...
            </div>
        </div>
    }
</div>

terimler_app_web/terimler_app_web/Views/YonetimOneriler/Sil.cshtml
@model Oneriler
@{
    ViewData["Title"] = "Sil";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<div class="card">
    <div class="card-heading border bottom">
        <br />
        <h4 class="card-title text-center">Terim Önerisi Sil</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-md-9 ml-auto mr-auto">
                <form asp-controller="YonetimOneriler" asp-action="Sil" method="post" enctype="multipart/form-data" class="form-horizontal mrg-top-40 pdd-right-30 ng-pristine ng-valid">
                    <div class="form-group">
                        <br />
                        <label>Gönderici Ad Soyad</label>
                        <input type="text" class="form-control" asp-for="AdSoyad" value="@Model.AdSoyad" readonly>
                    </div>
                    <div class="form-group">
                        <label>Gönderici Mail</label>
                        <input type="text" class="form-control" asp-for="TerimAd" value="@Model.TerimAd" readonly>
                    </div>
                    <div class="form-group">
                        <label>Terim Adı</label>
                        <input type="text" class="form-control" asp-for="TerimAd" value="@Model.TerimAd" readonly>
                    </div>
                    <div class="form-group">
                        <label>Terim Açıklaması</label>
                        <textarea class="form-control" asp-for="TerimAciklama" rows="5" readonly>@Model.TerimAciklama</textarea>
                    </div>
                    <div class="form-group">
                        <label>Terim Bölümü</label>
                        <input type="text" class="form-control" asp-for="TerimBolum" value="@Model.TerimBolum" readonly>
                    </div>
                    <center><button type="submit" class="btn btn-danger"><i class="fa fa-plus" aria-hidden="true"></i> Terim Önerisi Sil</button></center><br />
                </form>
            </div>
        </div>
    </div>
</div>