terimler_app_web/terimler_app_web/Controllers/Site/YonetimDuyurularController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using terimler_app_web.DataAccessLayer.Concrete;
using terimler_app_web.Filter;
using terimler_app_web.Models.Concrete;

namespace terimler_app_web.Controllers.Site
{
    [AuthFilter]
    public class YonetimDuyurularController : Controller
    {

        DuyurularOperations duyurularOperations = new DuyurularOperations("Duyurular");

        public IActionResult Index()
        {
            return View(duyurularOperations.GetAll().OrderByDescending(x => x.Id));
        }

        public IActionResult Incele(int id)
        {
            var item = duyurularOperations.GetById(id);
            if (item == null)
            {
                return RedirectToAction("Yonetim", "Hata");
            }
            return View(item);
        }

        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(Duyurular model)
        {
            if (ModelState.IsValid)
            {
                duyurularOperations.AddModel(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult Guncelle(int id)
        {
            var item = duyurularOperations.GetById(id);
            if (item == null)
            {
                return RedirectToAction("Yonetim", "Hata");
            }
            return View(item);
        }

        [HttpPost]
        public IActionResult Guncelle(int id, Duyurular newModel)
        {
            var model = duyurularOperations.GetById(id);

            model.Icerik = newModel.Icerik;
            model.Baslik = newModel.Baslik;
            model.EklenmeTarihi = newModel.EklenmeTarihi;

            duyurularOperations.UpdateModel(model);

            return RedirectToAction("Index");
        }

        public IActionResult Sil(int id)
        {
            var item = duyurularOperations.GetById(id);
            if (item == null)
            {
                return RedirectToAction("Yonetim", "Hata");
            }
            return View(item);
        }

        [HttpPost]
        public IActionResult Sil(int id, IFormCollection collection)
        {
            duyurularOperations.DeleteModel(id);
            return RedirectToAction("Index");
        }

    }
}

terimler_app_web/terimler_app_web/Views/YonetimDuyurular/Ekle.cshtml
@model Duyurular
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<div class="card">
    <div class="card-heading border bottom">
        <br />
        <h4 class="card-title text-center">Yeni Duyuru Ekle</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-md-9 ml-auto mr-auto">
                <form asp-controller="YonetimDuyurular" asp-action="Ekle" method="post" enctype="multipart/form-data" class="form-horizontal mrg-top-40 pdd-right-30 ng-pristine ng-valid">
                    <div class="form-group">
                        <br />
                        <label>Duyuru Başlık</label>
                        <input type="text" class="form-control kontrol" asp-for="Baslik" placeholder="Duyuru Başlığını Giriniz..." required>
                    </div>
                    <div class="form-group">
                        <label>Eklenme Tarihi</label>
                        <input type="text" class="form-control kontrol" asp-for="EklenmeTarihi" placeholder="Eklenme Tarihini Giriniz..." required>
                    </div>
                    <div class="form-group">
                        <label>Duyuru İçerik</label>
                        <textarea class="form-control" asp-for="Icerik" placeholder="Duyuru İçeriğini Giriniz..." rows="5" required></textarea>
                    </div>
                    <center><button type="submit" class="btn btn-info"><i class="fa fa-plus" aria-hidden="true"></i> Yeni Duyuru Ekle</button></center><br />
                </form>
            </div>
        </div>
    </div>
</div>

terimler_app_web/terimler_app_web/Views/YonetimDuyurular/Guncelle.cshtml
@model Duyurular
@{
    ViewData["Title"] = "Guncelle";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<div class="card">
    <div class="card-heading border bottom">
        <br />
        <h4 class="card-title text-center">Duyuru Güncelle</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-md-9 ml-auto mr-auto">
                <form asp-controller="YonetimDuyurular" asp-action="Guncelle" method="post" enctype="multipart/form-data" class="form-horizontal mrg-top-40 pdd-right-30 ng-pristine ng-valid">
                    <div class="form-group">
                        <br />
                        <label>Duyuru Başlık</label>
                        <input type="text" class="form-control kontrol" asp-for="Baslik" value="@Model.Baslik" required>
                    </div>
                    <div class="form-group">
                        <label>Eklenme Tarihi</label>
                        <input type="text" class="form-control kontrol" asp-for="EklenmeTarihi" value="@Model.EklenmeTarihi" required>
                    </div>
                    <div class="form-group">
                        <label>Duyuru İçerik</label>
                        <textarea class="form-control" asp-for="Icerik" rows="5" required>@Model.Icerik</textarea>
                    </div>
                    <center><button type="submit" class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i> Duyuru Güncelle</button></center><br />
                </form>
            </div>
        </div>
    </div>
</div>

terimler_app_web/terimler_app_web/Views/YonetimDuyurular/Incele.cshtml
@model Duyurular
@{
    ViewData["Title"] = "Incele";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<div class="card">
    <div class="card-heading border bottom">
        <br />
        <h4 class="card-title text-center">Duyuru İncele</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-md-9 ml-auto mr-auto">
                <form asp-controller="" asp-action="" method="post" enctype="multipart/form-data" class="form-horizontal mrg-top-40 pdd-right-30 ng-pristine ng-valid">
                    <div class="form-group">
                        <label>Eklenme Tarihi</label>
                        <input type="text" class="form-control" asp-for="EklenmeTarihi" value="@Model.EklenmeTarihi" readonly>
                    </div>
                    <div class="form-group">
                        <label>Duyuru Başlık</label>
                        <input type="text" class="form-control" asp-for="Baslik" value="@Model.Baslik" readonly>
                    </div>
                    <div class="form-group">
                        <label>Duyuru İçerik</label>
                        <textarea class="form-control" asp-for="Icerik" rows="5" readonly>@Model.Icerik</textarea>
                    </div>
                </form>
                <center><a href="/YonetimDuyurular/Index/" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Geriye Dön</a></center><br />
            </div>
        </div>
    </div>
</div>

terimler_app_web/terimler_app_web/Views/YonetimDuyurular/Index.cshtml
@model IEnumerable<Duyurular>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<script src="~/TemplateAdmin/Js/jquery-1.10.2.js"></script>
<script>
    $(document).ready(function () {
        $('#myTable').dataTable();
    });
</script>

<div class="container-fluid">
    @if (Model.Count() > 0)
    {
        <!-- Verileri Listeleme -->
        <div class="card mb-3 text-center">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Duyurular Listesi
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="myTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Başlık</th>
                                <th>Eklenme Tarihi</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @if(item.Baslik.Length > 30)
                                        {
                                            @item.Baslik.Substring(0,30)<span>...</span>
                                        }
                                        else
                                        {
                                            @item.Baslik
                                        }
                                    </td>
                                    <td>@item.EklenmeTarihi</td>
                                    <td>
                                        <a href="/YonetimDuyurular/Incele/@item.Id" class="btn btn-info btn-sm"><i class="fa fa-search" aria-hidden="true"></i> İncele</a>
                                        <a href="/YonetimDuyurular/Guncelle/@item.Id" class="btn btn-success btn-sm"><i class="fa fa-edit" aria-hidden="true"></i> Güncelle</a>
                                        <a href="/YonetimDuyurular/Sil/@item.Id" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i> Sil</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer small text-muted">Son Güncelleme Tarihi : @DateTime.Now</div>
        </div>

    }
    else
    {
        <div class="card mb-3 text-center">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Veri Bulunamadı
            </div>
            <div class="card-body">
                Eklenmiş Herhangi Bir Veri Bulunamadı...
            </div>
        </div>
    }
</div>

terimler_app_web/terimler_app_web/Views/YonetimDuyurular/Sil.cshtml
@model Duyurular
@{
    ViewData["Title"] = "Sil";
    Layout = "~/Views/Shared/_LayoutYonetim.cshtml";
}

<div class="card">
    <div class="card-heading border bottom">
        <br />
        <h4 class="card-title text-center">Duyuru Sil</h4>
    </div>
    <div class="card-block">
        <div class="row">
            <div class="col-md-9 ml-auto mr-auto">
                <form asp-controller="YonetimDuyurular" asp-action="Sil" method="post" enctype="multipart/form-data" class="form-horizontal mrg-top-40 pdd-right-30 ng-pristine ng-valid">
                    <div class="form-group">
                        <br />
                        <label>Duyuru Başlık</label>
                        <input type="text" class="form-control kontrol" asp-for="Baslik" value="@Model.Baslik" readonly>
                    </div>
                    <div class="form-group">
                        <label>Eklenme Tarihi</label>
                        <input type="text" class="form-control kontrol" asp-for="EklenmeTarihi" value="@Model.EklenmeTarihi" readonly>
                    </div>
                    <div class="form-group">
                        <label>Duyuru İçerik</label>
                        <textarea class="form-control" asp-for="Icerik" rows="5" readonly>@Model.Icerik</textarea>
                    </div>
                    <center><button type="submit" class="btn btn-danger"><i class="fa fa-plus" aria-hidden="true"></i> Duyuru Sil</button></center><br />
                </form>
            </div>
        </div>
    </div>
</div>